# BEV OSINT Framework - Request Multiplexer Configuration
# High-performance request multiplexing system configuration

# Core multiplexer settings
multiplexer:
  max_concurrency: 1000
  worker_count: 50
  request_timeout: 30.0
  retry_attempts: 3
  enable_caching: true
  cache_ttl: 300  # 5 minutes

# Connection pool configuration
connection_pool:
  max_connections: 500
  max_connections_per_host: 50
  connection_timeout: 30.0
  read_timeout: 30.0
  idle_timeout: 300  # 5 minutes
  max_connection_age: 3600  # 1 hour
  enable_proxy_rotation: true

  # Proxy rotation settings
  proxy_rotation:
    proxy_pool_url: "http://proxy-manager:8000"
    strategy: "best_performance"  # round_robin, least_used, best_performance, geographic
    health_check_interval: 60

# Rate limiting configuration
rate_limiting:
  redis_url: "redis://redis:6379/12"

  # Default rules
  rules:
    global:
      algorithm: "sliding_window"
      limit: 1000
      window: 60  # seconds

    per_host:
      algorithm: "token_bucket"
      limit: 100
      window: 60

    burst_protection:
      algorithm: "fixed_window"
      limit: 50
      window: 10

# Queue management configuration
queue_manager:
  queue_type: "rabbitmq"  # rabbitmq, kafka, redis, memory
  max_queue_size: 10000
  enable_backpressure: true
  backpressure_threshold: 8000
  backpressure_strategy: "drop_low_priority"  # drop_low_priority, delay, reject

  # RabbitMQ settings
  rabbitmq:
    url: "amqp://guest:guest@rabbitmq-1:5672/"
    exchange: "bev_requests"
    routing_rules:
      high_priority: "priority_queue"
      crawl: "crawler_queue"

  # Kafka settings
  kafka:
    brokers: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    topic_prefix: "bev_requests"

  # Redis settings
  redis:
    url: "redis://redis:6379/12"

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5
  timeout_duration: 60  # seconds
  request_timeout: 30

# Performance monitoring
monitoring:
  metrics_enabled: true
  prometheus_port: 9092
  health_check_interval: 30
  health_check_timeout: 10

# Logging configuration
logging:
  level: "INFO"
  format: "json"

# Security settings
security:
  enable_request_validation: true
  max_request_size: "10MB"
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"]

# Development/debugging
debug:
  enable_request_tracing: false
  log_request_details: false
  performance_profiling: false