FROM python:3.11-slim
LABEL maintainer="BEV DevOps"
WORKDIR /app
COPY src/alternative_market/dm_crawler.py ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1
HEALTHCHECK CMD ["python", "dm_crawler.py", "--healthcheck"]
CMD ["python", "dm_crawler.py"]
EXPOSE 8080
