version: '3.8'

# Oracle1-Cloud ARM Server (100.96.197.84)
# Research & Distributed Services (ARM-compatible)

services:
  # Lightweight Redis for distributed coordination
  redis-arm:
    image: redis:7-alpine
    container_name: bev_redis_oracle
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - bev_network

  # N8N workflow automation (ARM)
  n8n:
    image: n8nio/n8n:latest
    container_name: bev_n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASSWORD:-admin123}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - bev_network

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    container_name: bev_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - bev_network

  # Research crawler service (ARM Python)
  research_crawler:
    build:
      context: ../../
      dockerfile: docker/oracle/Dockerfile.research
    container_name: bev_research_crawler
    environment:
      REDIS_HOST: redis-arm
      THANOS_API: http://100.122.12.54:8000
    volumes:
      - crawler_data:/app/data
    restart: always
    networks:
      - bev_network

  # Intelligence processor (ARM Python)
  intel_processor:
    build:
      context: ../../
      dockerfile: docker/oracle/Dockerfile.intel
    container_name: bev_intel_processor
    environment:
      REDIS_HOST: redis-arm
      POSTGRES_HOST: 100.122.12.54
    volumes:
      - intel_data:/app/data
    restart: always
    networks:
      - bev_network

  # Proxy rotation service
  proxy_manager:
    build:
      context: ../../
      dockerfile: docker/oracle/Dockerfile.proxy
    container_name: bev_proxy_manager
    ports:
      - "8888:8888"
    volumes:
      - proxy_data:/app/proxies
    restart: always
    networks:
      - bev_network

volumes:
  redis_data:
  n8n_data:
  nginx_logs:
  crawler_data:
  intel_data:
  proxy_data:

networks:
  bev_network:
    driver: bridge
